ALTER TABLE proposal ADD COLUMN status VARCHAR(40) NOT NULL DEFAULT 'PENDING';

UPDATE task_order
SET status = CASE status
    WHEN 'DRAFT' THEN 'OPEN'
    WHEN 'PUBLISHED' THEN 'OPEN'
    WHEN 'CLOSED' THEN 'COMPLETED'
    ELSE status
END;
